In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df = pd.read_csv('/content/housefile3.csv')
df

   Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [ ]:
import math
median_bedrooms = math.floor(df.Bedrooms.median())
median_bedrooms

3

In [ ]:
df.Bedrooms = df.Bedrooms.fillna(median_bedrooms)
df

   Area  Bedrooms  Age   Price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000